# -*- coding: utf-8 -*-
"""ANN_Practise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oCdrFB477Lx0B2JxxLrHoSvALC96G4M
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('gld_price_data.csv')

df.head()

X = df[['SPX','USO','SLV','EUR/USD']]
y = df[['GLD']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = Sequential()

model.add(Dense(10, activation='relu',input_dim=4))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='linear'))

model.compile(optimizer='adam', loss='mean_squared_error')

history = model.fit(X_train_scaled,y_train,epochs=50,validation_split=0.1)

y_pred = model.predict(X_test_scaled)

from sklearn.metrics import r2_score

r2_score(y_test, y_pred)