# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPmyasWx8rHLKV8HUG8XJaVFjCzhj-RW
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('diabetes.csv')

df.head()

df.isnull().sum()

df.info()

X = df.drop('Outcome', axis=1)
y = df['Outcome']

X

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

import tensorflow as tf
 from tensorflow.keras.models import Sequential
 from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(8, activation='relu', input_shape=(8,)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10,batch_size=4, verbose =1)

score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])